DROP TABLE IF EXISTS contatos;

CREATE TABLE contatos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  canal VARCHAR(250) NOT NULL,
  valor VARCHAR(250) NOT NULL,
  obs VARCHAR(250) DEFAULT NULL
);